var config = {
    suits:["spade","daimond","club","heart"], 
    points:["A",2,3,4,5,6,7,8,9,10,"J","Q","K"], 
    cards:["杀","闪","桃","过河拆桥"],
    players:[
        {
            playerName:"sqwww",
            nation:"群",
            sex:"男",
            name:"吕布",
            hp:4,
            skill:null
        },
        {
            playerName:"sqwwwok",
            nation:"群",
            sex:"女",
            name:"貂蝉",
            hp:3,
            skill:null
        }],
    kurisu:false
}